### ISSUE TITLE
Add (hardness, chlorine, alkalinity, etc.)

### ISSUE THREAD

**Issue by jacobvalenzuela** [baliga-lab/aqxWeb#2]
Add (hardness, chlorine, alkalinity, etc.)

**Comment by weiju** [comment]
The development version now accepts hardness, chlorine and alkalinity, but with more measurement types we need to rework the user interface, at the moment, values for all types will be submitted at once, even the ones that were not set.

**Comment by weiju** [comment]
also need to add the graphs

**Comment by weiju** [comment]
additional measurement types are now available, still need to add graphs

**Comment by weiju** [comment]
graphs added
