### ISSUE TITLE
Add consortia

### ISSUE THREAD

**Issue by jacobvalenzuela** [baliga-lab/aqxWeb#5]
Add Consortia: multiple fish species

**Comment by weiju** [comment]
is this related to issue #4 or a request to allow multiple fish species in a system ?

**Comment by jacobvalenzuela** [comment]
It is related, but there should be an option for multiple species, I have catfish and shrimp.   So a box that would say "Does your system have multiple species?" then you can select multiple species for your system.

**Comment by weiju** [comment]
Our database model allows for multiple fish and plant species per system, I can add an option "Add another fish species..." to the web application, is that what is requested here ?

**Comment by jacobvalenzuela** [comment]
yes that would be great

Jacob J. Valenzuela, Ph.D.
Institute for Systems Biology
401 Terry Ave N
Seattle WA 98109
(206)-732-1496
https://www.systemsbiology.org
Jake.Valenzuela@systemsbiology.org

**Comment by weiju** [comment]
multiple fish and crops per system now implemented
